### ISSUE TITLE
some problem，plz~~~

### ISSUE THREAD

**Issue by pangzhiyu** [EchoRickZz/Pensieve-Pytorch#3]
Hello！
I ran your code。But I have some problem。Could you tell how to solve？
Thank you！

Traceback (most recent call last):
  File "D:\Pycode\2\Pensieve-Pytorch-master\rl_test_pytorch.py", line 183, in <module>
    main()
  File "D:\Pycode\2\Pensieve-Pytorch-master\rl_test_pytorch.py", line 56, in main
    log_file = open(log_path, 'w')
FileNotFoundError: [Errno 2] No such file or directory: './test_results/log_sim_rl_norway_tram_24'
Process Process-1:
Traceback (most recent call last):
  File "D:\Anaconda\envs\torch\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Anaconda\envs\torch\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Pycode\2\Pensieve-Pytorch-master\multi_pytorch.py", line 169, in central_agent
    reward_mean = testing(epoch,
  File "D:\Pycode\2\Pensieve-Pytorch-master\multi_pytorch.py", line 60, in testing
    test_log_files = os.listdir(TEST_LOG_FOLDER)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './test_results/'

**Comment by RuixiaoZhang** [comment]
Seems that you do not have the filepath './test_results/'. Just create one and try again.

**Comment by pangzhiyu** [comment]
> Seems that you do not have the filepath './test_results/'. Just create one and try again.

Thank you！ I solved it yesterday
And How many rounds does this code run？
Now I have run 1400 rounds
